#!/usr/bin/env zsh

set -x

# initialization
arch -arm64e sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="arch -arm64e sudo yabai --load-sa"

source ~/.config/yabai/initialization.sh

~/.config/yabai/recent-window-helper.sh init

# ====
# Signals
# ====

# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/initialization.sh"
yabai -m signal --add event=window_focused action="~/.config/yabai/change-window-border-color-when-window-focused.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=application_hidden action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_minimized action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_focused action="~/.config/yabai/recent-window-helper.sh record"

# ====
# Settings
# ====

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off

yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          off
yabai -m config window_border_width          2
yabai -m config window_border_radius         12
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xfcFFEE58
yabai -m config normal_window_border_color   0x00ffffff
yabai -m config insert_window_border_color   0xffd75f5f

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      96
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               32
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

# 3rd part border
borders blacklist="Min,weread,pasteV,paste-v,scrcpy,WeChat" active_color=0xfcfeee58 inactive_color=0x00494d64 width=5.0 &

# animation
yabai -m config window_animation_duration    1.5
yabai -m config window_animation_easing      ease_in_sine

# ====
# Rules
# ====

otherApp='^(IINA|访达|Calendar|日历|System Preferences|系统偏好设置|Mail|微信|WeChat|QQ|印象笔记|灵犀|网易云音乐|Tencent Lemon|企业微信|Todoist|Input Source Pro|Enpass|预览|scrcpy|文本编辑|Kap|Shottr|chatgpt|kimi|lobeChat|ChatGPT|Min|Kando|weread|pasteV|paste-v|Inoreader.*|飞书|fakeee)$'
yabai -m rule --add app="${otherApp}" manage=off sub-layer=below

yabai -m rule --add app=".*" layer=normal

## specific rule

yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on

yabai -m rule --add app="^Cursor$" title="^docked_cursor$" manage=off

yabai -m rule --apply

echo "yabai configuration loaded.."
