# 命令执行时间和格式
AGKOZAK_CMD_EXEC_TIME=1
AGKOZAK_CMD_EXEC_TIME_CHARS=( '~' '' )

# 最后展示的目录层级，超过的部分用...代替
AGKOZAK_PROMPT_DIRTRIM=4

# 命令执行状态和格式
AGKOZAK_COLORS_PATH='cyan'
AGKOZAK_MULTILINE=0
AGKOZAK_PROMPT_CHAR=( ❯ ❯ ❮ )
#AGKOZAK_COLORS_PROMPT_CHAR='magenta'
AGKOZAK_COLORS_PROMPT_CHAR='#F68C58'
AGKOZAK_USER_HOST_DISPLAY=0

# git 信息
# AGKOZAK_COLORS_BRANCH_STATUS='#E9F5CE'
AGKOZAK_COLORS_BRANCH_STATUS=243
AGKOZAK_CUSTOM_SYMBOLS=( '⇣⇡' '⇣' '⇡' '+' 'x' '!' '>' '?' 'S')

# python 虚拟环境
AGKOZAK_COLORS_VIRTUALENV='#F2F89D'
AGKOZAK_VIRTUALENV_CHARS=( ' ' '' )
